service: image-analysis-lambda

provider:
  name: aws
  runtime: nodejs12.x
  iamRoleStatements: 
    - Effect: "Allow"
      Action: 
        - rekognition:DetectLabels
      Resource: "*"
    - Effect: "Allow"
      Action: 
        - translate:TranslateText
      Resource: "*"

functions:
  image-recognition:
    handler: handler.main
    events:
      - http:
          path: recognize
          method: get